name: Expo build

on:
  push:
    tags: ['*']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      # Setup node
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x

      # Setup expo
      - name: Setup expo
        uses: expo/expo-github-action@v6
        with:
          expo-version: 4.x
          token: ${{ secrets.EXPO_CLI_TOKEN }}
          
      - run: yarn install
      - run: expo build:android -t apk
